version: "3.8"
services:
  frontend:
    container_name: home_portal_ui
    build:
      context: .
      target: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    tty: true
    stdin_open: true
