version: "3.8"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.12
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
      - ./mqtt/config/:/mosquitto/config
    ports:
      - "1883:1883"
      - "9001:9001"
    tty: true
networks:
  default:
    external:
      name: notdevs_proxy
