version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.12
    volumes:
      - ./backend/mqtt/config:/mosquitto/config/
    ports:
      - "1883:1883"
      - "8080:8080"
      - "9001:9001"
    # restart: unless-stopped
    networks:
      - host
networks:
  host:
